# Generated by Django 2.0 on 2017-12-21 07:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price_ago', models.CharField(max_length=255)),
                ('price_now', models.CharField(max_length=255)),
                ('feedback', models.CharField(max_length=255)),
                ('favorited', models.CharField(max_length=255)),
                ('img', models.FileField(upload_to='static/es_platform/img')),
            ],
            managers=[
                ('goods_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
