# Generated by Django 2.0 on 2017-12-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='good_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
