# Generated by Django 2.0 on 2017-12-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformes', '0003_auto_20171223_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='shipping',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='shop_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='shop_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='source_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='favorited',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='feedback',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price_ago',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price_now',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
