# Generated by Django 2.0 on 2017-12-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformes', '0004_auto_20171226_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='label',
            new_name='label_one',
        ),
        migrations.AddField(
            model_name='goods',
            name='label_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
