# Generated by Django 2.0 on 2017-12-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformes', '0006_auto_20171227_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.FileField(null=True, upload_to='static/es_platform/img'),
        ),
    ]
